kind: Pod
apiVersion: v1
metadata:
  name: nodelabels
  labels:
    env: development
spec:
    containers:
       - name: container1
         image: httpd
         command: ["/bin/bash", "-c", "while true; do echo Hello-ajay; sleep 300 ; done"]
    nodeSelector:                                         
       hardware: t2-medium
